---
title: "ISL ch 4 lab"
author: "Seung ji Nam"
date: '2020 1 13 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 4.6.1 The Stock Market Data
```{r}
library(ISLR)
names(Smarket)
dim(Smarket)
summary(Smarket)
```

```{r}
#cor(Smarket)
cor(Smarket[,-9])
```

```{r}
attach(Smarket)
plot(Volume)
```


## 4.6.2 Logistic Regression
```{r}
glm.fit= glm(Direction~ Lag1+Lag2+Lag3+Lag4+Lag5+Volume, family= binomial)
summary(glm.fit)
coef(glm.fit)
summary(glm.fit)$coef
summary(glm.fit)$coef[,4]
```

```{r}
glm.probs = predict(glm.fit, type='response')
glm.probs[1:10]

contrasts(Direction)

glm.pred = rep("Down", 1250)
glm.pred[glm.probs>0.5] ="Up"

table(glm.pred, Direction)
mean(glm.pred== Direction)
```

```{r}
train = (Year < 2005)
Smarket.2005 = Smarket[!train,]
dim(Smarket.2005)
Direction.2005 = Direction[!train]
```

```{r}
glm.fit= glm(Direction ~ Lag1 + Lag2 +Lag3 +Lag4 +Lag5 +Volume, data=Smarket, family= binomial, subset=train)
glm.probs= predict(glm.fit, Smarket.2005, type="response")
glm.pred = rep("Down", 252)
glm.pred[glm.probs>0.5] ="Up"
table(glm.pred, Direction.2005)
mean(glm.pred == Direction.2005)
mean(glm.pred!=Direction.2005)
```

### 4.6.3 Linear Discriminant Analysis

```{r}
library(MASS)
lda.fit = lda(Direction ~ Lag1 + Lag2, data= Smarket, subset= train)
lda.fit

plot(lda.fit)
```

```{r}
lda.pred = predict(lda.fit, Smarket.2005)
names(lda.pred)
```

```{r}
lda.class =lda.pred$class
table(lda.class, Direction.2005)
mean(lda.class == Direction.2005)


sum(lda.pred$posterior[,1]>= .5)
sum(lda.pred$posterior[,1]<= 0.5)

lda.pred$posterior[1:20, 1]
lda.class[1:20]

sum(lda.pred$posterior[,1]> 0.9)


```



### 4.6.4 Quadratic Discriminant Analysis
```{r}
dim(Caravan)
attach(Caravan)
summary(Purchase)
```


```{r}
standardized.X = scale(Caravan[,-86])
var(Caravan[,1])
var(Caravan[,2])

var(standardized.X[,1])
var(standardized.X[,2])
```

```{r}
library(class)
test = 1:1000
train.X = standardized.X[-test,]
test.X = standardized.X[test,]
train.Y = Purchase[-test]
test.Y = Purchase[test]
set.seed(730)
knn.pred = knn(train.X, test.X, train.Y, k=1)
mean(test.Y != knn.pred)
mean(test.Y != "No")

table(knn.pred, test.Y)
knn.pred = knn(train.X, test.X, train.Y, k=3)
table(knn.pred, test.Y)
knn.pred = knn(train.X, test.X, train.Y, k=5)
table(knn.pred, test.Y)
```

```{r}
glm.fit = glm(Purchase ~. , data= Caravan, family= binomial, subset= -test)
glm.probs = predict(glm.fit, Caravan[test,], type="response")
glm.pred = rep("No", 1000)
glm.pred [glm.probs > 0.5] = "Yes"
table(glm.pred, test.Y)
glm.pred = rep("No", 1000)
glm.pred[glm.probs>0.25] = "Yes"
table(glm.pred, test.Y)

```

